package ebpf

import (
	"bytes"
	"context"
	"encoding/binary"
	"time"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/sean-miningah/trace-desk/internal/core"
)

// procEvent mirrors `struct event` in process.bpf.c (same field order + sizes).
type procEvent struct {
	PID  uint32
	PPID uint32
	Comm [16]byte
}

// ProcessSource loads the exec/exit probe and implements core.EventSource,
// slotting in behind the same interface the fake source satisfied (M1).
type ProcessSource struct {
	objs processObjects // generated by bpf2go
	rd   *ringbuf.Reader
	lnk  link.Link
}

// New returns a ProcessSource ready to load its exec probe on Events.
func New() *ProcessSource { return &ProcessSource{} }


// Events implements core.EventSource.
func (s *ProcessSource) Events(ctx context.Context) (<-chan core.Event, error) {
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, err
	}
	if err := loadProcessObjects(&s.objs, nil); err != nil {
		return nil, err
	}
	lnk, err := link.Tracepoint("sched", "sched_process_exec", s.objs.HandleExec, nil)
	if err != nil {
		return nil, err
	}
	s.lnk = lnk
	rd, err := ringbuf.NewReader(s.objs.Events)
	if err != nil {
		return nil, err
	}
	s.rd = rd

	out := make(chan core.Event)
	go func() {
		defer close(out)
		go func() { <-ctx.Done(); _ = rd.Close() }()
		for {
			rec, err := rd.Read()
			if err != nil {
				return // os.ErrClosed on shutdown
			}
			var e procEvent
			if binary.Read(bytes.NewReader(rec.RawSample), binary.LittleEndian, &e) != nil {
				continue
			}
			out <- core.Event{
				Type:        core.ProcessExec,
				Timestamp:   time.Now(),
				PID:         e.PID,
				PPID:        e.PPID,
				ProcessName: string(bytes.TrimRight(e.Comm[:], "\x00")),
				Data:        core.ProcessData{Command: string(bytes.TrimRight(e.Comm[:], "\x00"))},
			}
		}
	}()
	return out, nil
}

// Close implements core.EventSource.
func (s *ProcessSource) Close() error {
	if s.rd != nil {
		_ = s.rd.Close()
	}
	if s.lnk != nil {
		_ = s.lnk.Close()
	}
	return s.objs.Close()
}
